[package]
authors = ["zhengxin <zhngxin@aliyun.com>"]
edition = "2018"
name = "encodingbufreader"
version = "0.1.0"
license = "MIT"
description = "A BuferReader with encoding."
[dependencies]
encoding = "0.2.33"
